### ISSUE TITLE
Profile Resource

### ISSUE THREAD

**Issue by lestece** [lestece/fit-u-api#1]
The profiles App allows us to list all the profiles, retrieve a single user by ID, profile owners can edit their own profiles.

## Tasks:
- [x] Create the ProfileList view with the GET method 
- [x] Write the ProfileSerializer class 
- [x] Create the ProfileDetail view with the GET and PUT method
- [x] Add Authentication and Authorization for PUT method
