### ISSUE TITLE
Set Up

### ISSUE THREAD

**Issue by lestece** [lestece/fit-u-api#2]
** Create the Django project and set it up to use Cloudinary for media files **

## Tasks:
- [x] Install Django
- [x] Start the fit_u_api project
- [x] Install the Django Cloudinary storage library
- [x] Install Pillow library for image processing
- [x] Create the env.py file for Cloudinary env var
- [x] Set up the settings.py file
